CREATE DATABASE BLOGSDB;

\c BLOGSDB;

CREATE TABLE BLOGS (
    ID INT PRIMARY KEY NOT NULL,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    CONTENT TEXT NOT NULL,
    CREATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DRAFT BOOLEAN
);