FROM golang:latest as base

WORKDIR /app

COPY . /app 
RUN go mod tidy
RUN go mod vendor

FROM base as build 
RUN CGO_ENABLED=0 GOOS=linux GO111MODULE=on go build -mod=vendor -a -o dmblogs-backend .

FROM base as unit-test
RUN go test -v ./...

FROM alpine:latest
COPY --from=build /app/dmblogs-backend .

EXPOSE 8000:8000

CMD [ "./dmblogs-backend" ]
