CREATE DATABASE blogapp;
CREATE USER danglingmind WITH ENCRYPTED PASSWORD '#ricky2327';
GRANT ALL PRIVILEGES ON DATABASE blogapp TO danglingmind;

-- #\c danglingmind; OR $psql -U danglingmind blogapp;

CREATE TABLE BLOGS (
    ID SERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    CONTENT TEXT NOT NULL,
    CREATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DRAFT BOOLEAN DEFAULT TRUE,
    CHECK TITLE <> ''
);

CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    FIRSTNAME TEXT NOT NULL CHECK (FIRSTNAME <> ''),
    MIDDLENAME TEXT,
    LASTNAME TEXT,
    COUNTRYCODE CHAR(3) NOT NULL,
    MOBILE CHAR(10) NOT NULL UNIQUE CHECK(MOBILE <> ''),
    EMAIL TEXT NOT NULL UNIQUE CHECK(EMAIL <> ''),
    PASSWORD TEXT NOT NULL CHECK (PASSWORD <> ''),
    CREATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    MODIFIED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ACTIVE BOOLEAN DEFAULT TRUE
);


/*
 psql -U postgres;
 drop owned by danglingmind;
 drop user danglingmind;

 */