CREATE DATABASE DEMOSHOP;

USE DEMOSHOP;

-- Products table 
CREATE TABLE PRODUCTS {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHAR(100) NOT NULL,
    PRICE FLOAT(5),
    CATEGORY CHAR(30),
    SUBCATEGORY CHAR(30),
    SOLD_TOTAL INTEGER,
    ADDED TIMESTAMP, 
    MODIFIED TIMESTAMP, 
    ACTIVE BOOL,
    PRODUCT_VERSION CHAR(6),
    PRIMARY KEY (ID)
};

-- Price table 
CREATE TABLE PRICE {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PRODUCTID INTEGER,
    PRICE FLOAT(5),
    CURRENCY CHAR(3),
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS
};

-- category table 
CREATE TABLE CATEGORY {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHAR(30) NOT NULL;
    ADDED TIMESTAMP,
    MODIFIED TIMESTAMP,
    ACTIVE BOOL,
    BETA BOOL,
    PRIMARY KEY (ID)
};

-- subcategory table
CREATE TABLE SUBCATEGORY {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHAR(30) NOT NULL,
    ADDED TIMESTAMP,
    MODIFIED TIMESTAMP,
    ACTIVE BOOL,
    BETA BOOL,
    PRIMARY KEY (ID)
};

-- relation between category and subcategory 
CREATE TABLE SUBCATEGORY_CATEGORY_RELATION {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CATEGORYID INTEGER, 
    SUBCATEGORYID INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY (ID);
    FOREIGN KEY (SUBCATEGORYID) REFERENCES SUBCATEGORY (ID);
};

-- Different plaforms for products
CREATE TABLE PLATFORMS {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHAR(30) NOT NULL,
    ADDED TIMESTAMP,
    MODIFIED TIMESTAMP,
    ACTIVE BOOL,
    BETA BOOL,
    PRIMARY KEY (ID)
};

-- platform versions
CREATE TABLE PLATFORM_VERSION {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PLATFORMID INTEGER,
    NAME CHAR(30) NOT NULL,
    ADDED TIMESTAMP,
    MODIFIED TIMESTAMP,
    ACTIVE BOOL,
    BETA BOOL, 
    NOTE CHAR(200),
    PRIMARY KEY (ID),
    FOREIGN KEY (PLATFORMID) REFERENCES PLATFORMS (ID);
};

-- files of the products
CREATE TABLE FILE {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PRODUCTID INTEGER,
    PATH MEDIUMTEXT,
    TYPE CHAR(10),
    ADDED TIMESTAMP,
    MODIFIED TIMESTAMP,
    BETA BOOL
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT (ID);
};

-- comments on the product
CREATE TABLE COMMENT {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USERID INTEGER,
    COMMENT MEDIUMTEXT,
    ADDED TIMESTAMP,
    MODIFIED TIMESTAMP,
    PRIMARY KEY (ID),
};

-- rating of the product
CREATE TABLE RATING {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USERID INTEGER,
    PRODUCTID INTEGER,
    RATING FLOAT(3),
    ADDED TIMESTAMP,
    MODIFIED TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (USERID)
        REFERENCES USER (ID);
};

-- orders as an entity 
CREATE TABLE ORDER {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USERID INTEGER,
    ORDERTIME TIMESTAMP,
    SALETYPE CHAR(10),
    PAYMENTID INTEGER,
    TRANSACTIONSTATUS CHAR(10),
    PAID BOOL,
    PAYMENTTIME TIMESTAMP,
    DELIVERYTIME TIMESTAMP,
    DELIVERYID INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (USERID)
        REFERENCES USER (ID);
    FOREIGN KEY (PAYMENTID)
        REFERENCES PAYMENT (ID);
    FOREIGN KEY (DELIVERYID)
        REFERENCES DELIVERY (ID);
};

CREATE TABLE ORDERDETAILS {
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PRODUCTID INTEGER,
    PRICE FLOAT(5),
    QUANTITY INTEGER,
    DISCOUNT FLOAT(3),
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCTS;
};