create database userdb;

\c userdb;

CREATE TABLE USERS (
    ID INT PRIMARY KEY NOT NULL,
    FIRSTNAME TEXT NOT NULL,
    MIDDLENAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL,
    COUNTRYCODE CHAR(3),
    MOBILE CHAR(10),
    EMAIL TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    CREATED TIMESTAMP,
    MODIFIED TIMESTAMP,
    ACTIVE BOOLEAN
);